name: Build

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

env:
  PYTHONIOENCODING: utf-8
  UV_VERSION: "0.7.2"
  TARGET_PYTHON: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.TARGET_PYTHON }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.TARGET_PYTHON }}

      - name: Install uv ${{ env.UV_VERSION }}
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Install all dependencies
        run: uv sync --all-groups

      - name: Build release distributions
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
